repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.3'  # Use the latest SHA or tag from the mirrors-prettier repository
    hooks:
      - id: prettier
        args: ['--write', '--parser', 'html']
        additional_dependencies: ['prettier@latest']
        files: \.(html|htm)$
